<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cajero.BLL\Cajero.BLL.csproj" />
		<ProjectReference Include="..\Cajerro.DAL\Cajerro.DAL.csproj" />
		<ProjectReference Include="..\Cajero.Hardware\Cajero.Hardware.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Boveda.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Transacciones.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Usuarios.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
